# Use default buffer sizes.

---
- name: default_memory_and_buffer
  hosts: ubuntu
  become: yes
  roles:
    - role: ../roles/common
      vars:

        test_name: "default_memory_and_buffer" # Which test is it? Remember to change this in each test. Used to make result dir.

        afpacket_ringsize: 2048
        afpacket_blocksize: 32768
        max_pending_packets: 1024

        default_memory: yes

        threading_management_cpu: '"16", "48"'
        threading_worker_cpu: '"1-10"'

        afpacket_threads_1: 10 # Threads in CPU group 1
        afpacket_threads_2: 0 # Threads in CPU group 2

        # Testing (Uncomment to quickly override defaults)
        # counters: "capture.kernel_packets,capture.kernel_drops" # Comma separated. Which counters to plot with suri-stats.
        # test_seconds: 10 # How long to test.