# 2 management threads node 1.

---
- name: mgmt_node1
  hosts: ubuntu
  become: yes
  roles:
    - role: ../roles/common
      vars:

        test_name: "mgmt_node1" # Which test is it? Remember to change this in each test. Used to make result dir.

        threading_management_cpu: '"16", "48"'
        threading_worker_cpu: '"1-15", "32-47"'

        afpacket_threads_1: 15 # Threads in CPU group 1
        afpacket_threads_2: 16 # Threads in CPU group 2

        # Testing (Uncomment to quickly override defaults)
        # counters: "capture.kernel_packets,capture.kernel_drops" # Comma separated. Which counters to plot with suri-stats.
        # test_seconds: 10 # How long to test.