---
- name: Setup Suricata
  hosts: ubuntu # Group in ansible hosts file.
  become: yes # Become root.
  vars:
    mgmt_nic: "eno1"

    afpacket_interface: "{{mgmt_nic}}"
    afpacket_threads: "{{(ansible_processor_vcpus/2) | int}}" # Use half of available threads
    afpacket_clustertype: "cluster-qm"
    afpacket_defrag: "no"
    afpacket_usemmap: "yes"
    afpacket_mmaplocked: "yes"
    afpacket_tpacketv3: "yes"
    afpacket_ringsize: 100000
    afpacket_blocksize: 1048576

    threading_management_cpu: 0
    threading_receive_cpu: "0-1"
    threading_worker_cpu: 1
    threading_worker_prio_low: 0
    threading_worker_prio_medium: 1
    threading_worker_prio_high: 1
    threading_worker_prio_default: "high"

    max_pending_packets: 65500 # Default is 1024
    runmode: "workers" # default is autofp
    default_packet_size: 9000 # see 'maxmtu' result when $ ip -d link list
    
  tasks:

    - name: install system updates for centos systems
      yum: name=* state=latest
      when: ansible_distribution == "CentOS"

    - name: install system updates for ubuntu systems
      apt: upgrade=dist
      when: ansible_distribution == "Ubuntu"

    - name: Set passwordless sudo # To prevent entering the password when ansible executes.
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      
    - name: Install packages
      package:
        name:
          - suricata # IDS
          - jq  # Command-line JSON processor
          - ethtool # Query or control network driver and hardware settings
          - build-essential # For compiling Intel driver
        state: latest

    - name: Install Intel i40e kernel module
      block:
        - name: Make sure directory exists
          file:
            path: /opt/i40e
            state: directory

        - name: Download and unarchive makefile from source
          unarchive:
            src: https://sourceforge.net/projects/e1000/files/i40e%20stable/2.14.13/i40e-2.14.13.tar.gz
            dest: /opt/i40e/
            remote_src: yes
            creates: i40e-2.14.13

        - name: Compile driver
          community.general.make:
            chdir: /opt/i40e/i40e-2.14.13/src
            target: install

        - name: Add the i40e module
          community.general.modprobe:
            name: i40e
            state: present

    - name: Set irq affinity
      command: "/opt/i40e/i40e-2.14.13/scripts/set_irq_affinity local {{mgmt_nic}}"

    - name: Stop irqbalance for high performance optimisation 
      service:
        name: irqbalance
        state: stopped

    - name: Configure NIC
      ignore_errors: yes
      block:

        - name: Change the number of RSS queues
          command: "ethtool -L {{mgmt_nic}} combined 1"

        - name: Enable receive hashing offload
          command: "ethtool -K {{mgmt_nic}} rxhash on"

        - name: Enable Rx ntuple filters and actions
          command: "ethtool -K {{mgmt_nic}} ntuple on"

        - name: Make RSS symmetric
          command: "ethtool -X {{mgmt_nic}} hkey 6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A equal 16"

        - name: Disable RX pause. # TODO: tx off?
          command: "ethtool -A {{mgmt_nic}} rx off"

        - name: Adaptive control is disabled for lowest possible latency
          command: "ethtool -C {{mgmt_nic}} adaptive-rx off adaptive-tx off rx-usecs 125"

        - name: Changes the number of ring entries for the Rx ring. # TODO: test
          command: "ethtool -G {{mgmt_nic}} rx 1024"

        - name: Make sure the RSS hash function is Toeplitz.
          command: "ethtool -X {{mgmt_nic}} hfunc toeplitz"

        - name: Let the NIC balance as much as possible # TODO: test sdfn vs sd
          shell: |
            for proto in tcp4 udp4 tcp6 udp6; do
              ethtool -N {{mgmt_nic}} rx-flow-hash $proto sdfn
            done

    - name: Configure suricata  
      template:  
        src: suricata.yaml.j2  
        dest: /etc/suricata/suricata.yaml  

    - name: Update signatures
      command: suricata-update

    - name: Start suricata
      service:
        name: suricata
        state: restarted
        enabled: yes
