# NIC is on NUMA 0. What happens if we run on NUMA 1?
# AKA the opposite of test 1.
# We can use all 32 CPUs on NUMA node 1 as workers.

---
- name: mgmt-cpu-0-and-32
  hosts: ubuntu
  become: yes
  roles:
    - role: common
      vars:
        test_name: "mgmt-node0" # Which test is it? Remember to change this in each test. Used to make result dir.
        threading_management_cpu: '"0-10"'
        threading_worker_cpu: '"16-31", "48-63"'

        afpacket_threads_1: 16 # Threads in CPU group 1
        afpacket_threads_2: 16 # Threads in CPU group 2    

        outputs_fast_enabled: "yes"
        defrag_memcap: "32mb"
        defrag_timeout: "60"
        flow_memcap: "128mb"
        flow_hash_size: "65536"
        flow_prealloc: "10000"
        stream_memcap: "64mb"
        stream_checksum_validation: "yes"
        stream_prealloc_sessions: "2000"
        # Inspection will be skipped when stream.reassembly.depth is reached for a particular flow.
        stream_bypass: "no"
        stream_reassembly_memcap: "256mb"
        stream_reassembly_segment_prealloc: "2048"
        detect_profile: "medium"
        detect_prefilter: "mpm"

        # Testing (Uncomment to quickly override defaults)
        # counters: "capture.kernel_packets,capture.kernel_drops" # Comma separated. Which counters to plot with suri-stats.
        # test_seconds: 10 # How long to test.