# Test 1, but one mgmt CPU on same node.

---
- name: Test 3 - NUMA 0 one mgmt
  hosts: ubuntu
  become: yes
  roles:
    - role: common
      vars:
        test_name: "test3" # Which test is it? Remember to change this in each test. Used to make result dir.
        threading_management_cpu: '"0"'
        threading_worker_cpu: '"1-15", "32-47"'

        afpacket_threads_1: 15 # Threads in CPU group 1
        afpacket_threads_2: 16 # Threads in CPU group 2
        
        # Testing (Uncomment to quickly override defaults)
        # counters: "capture.kernel_packets,capture.kernel_drops" # Comma separated. Which counters to plot with suri-stats.
        # test_seconds: 10 # How long to test.