# Management on two first CPU in each group, 0-1 and 32-33.

---
- name: Test 7 - two mgmt on node
  hosts: ubuntu
  become: yes
  roles:
    - role: common
      vars:
        test_name: "test7" # Which test is it? Remember to change this in each test. Used to make result dir.
        threading_management_cpu: '"0-1", "32-33"'
        threading_worker_cpu: '"2-15", "34-47"'
        
        afpacket_threads_1: 14 # Threads in CPU group 1
        afpacket_threads_2: 14 # Threads in CPU group 2