# SETUP 5
# Only use one CPU group.

---
- name: Test 5 - one cpu group
  hosts: ubuntu
  become: yes
  roles:
    - role: common
      vars:
        test_name: "test5" # Which test is it? Remember to change this in each test. Used to make result dir.
        threading_management_cpu: '"16"'
        threading_worker_cpu: '"17-31"'

        # Testing
        counters: "capture.kernel_packets,capture.kernel_drops" # Comma separated. Which counters to plot with suri-stats.
        test_seconds: 5 # How long to test.