# SETUP 1
# Follows Suricata 9.5.2.1 https://suricata.readthedocs.io/en/suricata-6.0.0/performance/high-performance-config.html
# Sniffing NIC (eno1) is located on NUMA 0.
# Hence, Suricata needs to run on the same node.
# CPU 0 is widely used by many services in Linux. Hence, we never use CPU 0.

# TODO: isolcpus=1-15,32-47
---
- name: Test 4 - 
  hosts: ubuntu
  become: yes
  roles:
    - role: common
      vars:
        test_name: "test4" # Which test is it? Remember to change this in each test. Used to make result dir.
        threading_management_cpu: '0'
        threading_worker_cpu: '"1-15", "32-47"'
        threading_worker_prio_low: "" # TODO: Test
        threading_worker_prio_medium: "" # TODO: Test
        threading_worker_prio_high: "" # TODO: Test