# Follows Suricata 9.5.2.1 https://suricata.readthedocs.io/en/suricata-6.0.0/performance/high-performance-config.html
# Sniffing NIC is located on NUMA 1.
# Hence, Suricata needs to run on the same node.

---
- name: Test 1 - NUMA 1
  hosts: ubuntu
  become: yes
  roles:
    - role: common
      vars:
        test_name: "test1" # Which test is it? Remember to change this in each test. Used to make result dir.
        threading_management_cpu: '"16"'
        threading_worker_cpu: '"17-31", "48-63"'

        # Testing
        counters: "capture.kernel_packets,capture.kernel_drops" # Comma separated. Which counters to plot with suri-stats.
        test_seconds: 5 # How long to test.