# SETUP 5
# NIC is on NUMA 0. What happens if we run on NUMA 1, 
# leaving the first CPU on the NODE for management?

# TODO: isolcpus=1-16
---
- name: Test 5 -
  hosts: ubuntu
  become: yes
  roles:
    - role: common
      vars:
        test_name: "test5" # Which test is it? Remember to change this in each test. Used to make result dir.
        threading_management_cpu: '0'
        threading_worker_cpu: '"1-15"'
        threading_worker_prio_low: "" # TODO: Test
        threading_worker_prio_medium: "" # TODO: Test
        threading_worker_prio_high: "" # TODO: Test