# monitor_if: "{{MONITOR_IF}}"
monitor_if: "ens2f0" # $ sudo lshw -class network -short

# Default configuration.
default: no

# Default memory allication and no local bypass.
default_memory: no

# High performance BIOS settings.
bios: yes

# NIC ring descriptor size
rx_ring: 1024 # Default 1024. 512 and 2048 yield worse results

# All CPUs in a set, e.g. 0-63
cpu_set: "0-{{ansible_processor_vcpus - 1}}"

threading_set_cpu_affinity: 'yes'
threading_management_cpu: '0'
threading_receive_cpu: '{{threading_management_cpu}}' # This is not used for workers runmode, only autofp. For safe measure, we set equal to mgmt.
threading_worker_cpu: '"1-15", "33-47"'
threading_worker_cpu_plain: "{{threading_worker_cpu|regex_replace('[\x20\x22]', '')}}"
threading_worker_prio_low: ''
threading_worker_prio_medium: '{{threading_management_cpu}}'
threading_worker_prio_high: '{{threading_worker_cpu}}'
threading_worker_prio_default: "high"

afpacket_interface: "{{monitor_if}}"
afpacket_threads_1: 15 # Threads in CPU group 1
afpacket_threads_2: "{{afpacket_threads_1}}" # Threads in CPU group 2
afpacket_clustertype: "cluster_qm" # To bind Suricata to RSS queues
afpacket_defrag: "no" # TODO: test yes/no, trenger kun å teste med beste test?
afpacket_usemmap: "yes"
afpacket_mmaplocked: "yes"
afpacket_tpacketv3: "yes"

# Ring-size is another af-packet variable that can be considered for tuning
# and performance benefits. It basically means the buffer size for packets 
# per thread.
# Default : 2048
# SEPTun setting : 200000
# SEPTun 2/redipranha setting : 300000
afpacket_ringsize: 200000

# SEPTun/default setting : 1048576
# SEPTun 2/redipranha setting : 2097152
afpacket_blocksize: 2097152

# To deal with high traffic, we set the max-pending-packets to maximum value 65500.
# Should not need any testing, leave at 65500.
# Default is 1024
max_pending_packets: 65500

runmode: "workers" # default is autofp

# Related to memory and emergency mode. See redpiranha under "Suricata Config".
# All values 
flow_memcap: "{{'128mb' if default_memory else '14gb'}}"
flow_hash_size: "{{'65536' if default_memory else '256072'}}"
flow_prealloc: "{{'10000' if default_memory else '300000'}}"
stream_memcap: "{{'64mb' if default_memory else '12gb'}}"
stream_checksum_validation: yes # "{{'yes' if default_memory else 'no'}}"
stream_prealloc_sessions: "{{'2000' if default_memory else '375000'}}"
# Inspection will be skipped when stream.reassembly.depth is reached for a particular flow.
stream_bypass: "{{'no' if default_memory else 'yes'}}"
stream_reassembly_memcap: "{{'256mb' if default_memory else '20gb'}}"
stream_reassembly_segment_prealloc: "{{'2048' if default_memory else '200000'}}"

# Testing
counters: "capture.kernel_packets,capture.kernel_drops,tcp.reassembly_gap" # Comma separated. Which counters to plot with suri-stats.
test_seconds: 120 # How long to test.
test_name: "test1" # Which test is it? Remember to change this in each test. Used to make result dir.
traffic_gb: 9 # max 10.
