# monitor_if: "{{MONITOR_IF}}"
monitor_if: "ens2f0" # $ sudo lshw -class network -short

# Whether configuration should be default or not.
default: no

# NIC ring descriptor size
rx_ring: 1024 # Default 1024. 512 and 2048 yield worse results

# All CPUs in a set, e.g. 0-63
cpu_set: "0-{{ansible_processor_vcpus - 1}}"

threading_set_cpu_affinity: 'yes'
threading_management_cpu: '0'
threading_receive_cpu: '{{threading_management_cpu}}' # This is not used for workers runmode, only autofp. For safe measure, we set equal to mgmt.
threading_worker_cpu: '"1-15", "33-47"'
threading_worker_cpu_plain: "{{threading_worker_cpu|regex_replace('[\x20\x22]', '')}}"
threading_worker_prio_low: ''
threading_worker_prio_medium: '{{threading_management_cpu}}'
threading_worker_prio_high: '{{threading_worker_cpu}}'
threading_worker_prio_default: "high"

afpacket_interface: "{{monitor_if}}"
afpacket_threads_1: 15 # Threads in CPU group 1
afpacket_threads_2: "{{afpacket_threads_1}}" # Threads in CPU group 2
afpacket_clustertype: "cluster_qm" # To bind Suricata to RSS queues
afpacket_defrag: "no" # TODO: test yes/no, trenger kun å teste med beste test?
afpacket_usemmap: "yes"
afpacket_mmaplocked: "yes"
afpacket_tpacketv3: "yes"

# Ring-size is another af-packet variable that can be considered for tuning
# and performance benefits. It basically means the buffer size for packets 
# per thread.
# Default : 2048
# SEPTun setting : 200000
# SEPTun 2/redipranha setting : 300000
afpacket_ringsize: 200000

# SEPTun/default setting : 1048576
# SEPTun 2/redipranha setting : 2097152
afpacket_blocksize: 2097152

# To deal with high traffic, we set the max-pending-packets to maximum value 65500.
# Should not need any testing, leave at 65500.
# Default is 1024
max_pending_packets: 65500

runmode: "workers" # default is autofp

# Related to memory and emergency mode. See redpiranha under "Suricata Config".
# All values 
outputs_fast_enabled: "{{'yes' if default else 'no'}}"
defrag_memcap: "{{'32mb' if default else '1gb'}}"
defrag_timeout: "{{'60' if default else '10'}}"
flow_timeouts_default_established: "{{'300' if default else '60'}}"
flow_timeouts_tcp_new: "{{'60' if default else '30'}}"
flow_timeouts_tcp_emergency_new: "{{'5' if default else '1'}}"
flow_timeouts_udp_established: "{{'300' if default else '60'}}"
flow_timeouts_icmp_established: "{{'300' if default else '60'}}"
flow_memcap: "{{'128mb' if default else '18gb'}}"
flow_hash_size: "{{'65536' if default else '256072'}}"
flow_prealloc: "{{'10000' if default else '300000'}}"
stream_memcap: "{{'64mb' if default else '12gb'}}"
stream_checksum_validation: "{{'yes' if default else 'no'}}"
stream_prealloc_sessions: "{{'2000' if default else '200000'}}"
# Inspection will be skipped when stream.reassembly.depth is reached for a particular flow.
stream_bypass: "{{'no' if default else 'yes'}}"
stream_reassembly_memcap: "{{'256mb' if default else '24gb'}}"
stream_reassembly_segment_prealloc: "{{'2048' if default else '200000'}}"
detect_profile: "{{'medium' if default else 'high'}}"
detect_prefilter: "{{'mpm' if default else 'auto'}}"

# Testing
counters: "capture.kernel_packets,capture.kernel_drops,tcp.reassembly_gap" # Comma separated. Which counters to plot with suri-stats.
test_seconds: 300 # How long to test.
test_name: "test1" # Which test is it? Remember to change this in each test. Used to make result dir.
