# monitor_if: "{{MONITOR_IF}}"
monitor_if: "ens2f0" # $ sudo lshw -class network -short

# Whether configuration should be default or not.
default: no

# NIC ring descriptor size
rx_ring: 1024 # Default 1024. 512 and 2048 yield worse results

# All CPUs in a set, e.g. 0-63
cpu_set: "0-{{ansible_processor_vcpus - 1}}"

threading_set_cpu_affinity: 'yes'
threading_management_cpu: '0'
threading_receive_cpu: '{{threading_management_cpu}}' # This is not used for workers runmode, only autofp. For safe measure, we set equal to mgmt.
threading_worker_cpu: '"1-15", "33-47"'
threading_worker_cpu_plain: "{{threading_worker_cpu|regex_replace('[\x20\x22]', '')}}"
threading_worker_prio_low: ''
threading_worker_prio_medium: '{{threading_management_cpu}}'
threading_worker_prio_high: '{{threading_worker_cpu}}'
threading_worker_prio_default: "high"

afpacket_interface: "{{monitor_if}}"
afpacket_threads_1: 15 # Threads in CPU group 1
afpacket_threads_2: "{{afpacket_threads_1}}" # Threads in CPU group 2
afpacket_clustertype: "cluster_qm" # To bind Suricata to RSS queues
afpacket_defrag: "no" # TODO: test yes/no, trenger kun å teste med beste test?
afpacket_usemmap: "yes"
afpacket_mmaplocked: "yes"
afpacket_tpacketv3: "yes"

# Ring-size is another af-packet variable that can be considered for tuning
# and performance benefits. It basically means the buffer size for packets 
# per thread.
# Default : 2048
# SEPTun setting : 200000
# SEPTun 2/redipranha setting : 300000
afpacket_ringsize: 200000

# SEPTun/default setting : 1048576
# SEPTun 2/redipranha setting : 2097152
afpacket_blocksize: 2097152

# To deal with high traffic, we set the max-pending-packets to maximum value 65500.
# Should not need any testing, leave at 65500.
# Default is 1024
max_pending_packets: 65500

runmode: "workers" # default is autofp

# Related to memory and emergency mode. See redpiranha under "Suricata Config"
outputs_fast_enabled: no # default: yes
outputs_eve_log_filetype: "syslog" #default: regular
defrag_memcap: "1gb" # default: 32mb
defrag_timeout: 10 # default: 60
flow_timeouts_default_established: 60 # default: 300
flow_timeouts_tcp_new: 30 # default: 60
flow_timeouts_tcp_emergency_new: 1 # default: 5
flow_timeouts_udp_established: 60 # default: 300
flow_timeouts_icmp_established: 60 # default: 300
flow_memcap: "18gb" # default: 128mb
flow_hash_size: 256072 # default: 65536
flow_prealloc: 300000 # default: 10000
stream_memcap: "12gb" # default: 64mb
stream_checksum_validation: no # default: yes
stream_prealloc_sessions: 200000 # default: 2000
# Inspection will be skipped when stream.reassembly.depth is reached for a particular flow.
stream_bypass: yes # Deafult: no
stream_reassembly_memcap: "24gb" # default: 256mb
stream_reassembly_segment_prealloc: 200000 # default: 2048
detect_profile: "high" # default: medium
detect_prefilter: "auto" # default: mpm

# Testing
counters: "capture.kernel_packets,capture.kernel_drops,tcp.reassembly_gap" # Comma separated. Which counters to plot with suri-stats.
test_seconds: 300 # How long to test.
test_name: "test1" # Which test is it? Remember to change this in each test. Used to make result dir.
