---
- name: cpu_15
  hosts: ubuntu
  become: yes
  roles:
    - role: ../roles/common
      vars:

        test_name: "cpu_15" # Which test is it? Remember to change this in each test. Used to make result dir.

        threading_management_cpu: '"0", "32"'
        threading_worker_cpu: '"1-15"'

        afpacket_threads_1: 15 # Threads in CPU group 1
        afpacket_threads_2: 0 # Threads in CPU group 2