---

- name: Set passwordless sudo # To prevent entering the password when ansible executes.
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  
  - name: Reboot to set NIC values to default
  reboot:

- name: Install packages
  package:
    name:
      - suricata # IDS
      - jq  # Command-line JSON processor
      - ethtool # Query or control network driver and hardware settings
      - build-essential # For compiling Intel driver
      - linux-tools-generic # Installing Perf for testing
      - linux-tools-5.4.0-72-generic # Installing Perf for testing
      - sysstat # For CPU utilization output
    state: latest

- name: Stops irqbalance for high performance optimisation 
  service:
    name: irqbalance
    state: stopped

- name: Set irq affinity
  command: "/opt/i40e/i40e-2.14.13/scripts/set_irq_affinity {{irq_affinity_cpu}} {{monitor_if}}" # "local" means NUMA 0.

- name: Configure NIC
  ignore_errors: yes
  block:
    - name: Change the number of RSS queues
      command: "ethtool -L 1"

- name: Configure suricata  
  template:  
    src: suricata.yaml.j2  
    dest: /etc/suricata/suricata.yaml 

- name: Update signatures
  command: suricata-update

- name: Restart suricata
  service:
    name: suricata
    state: restarted
    enabled: yes