---

- name: Set passwordless sudo # To prevent entering the password when ansible executes.
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  
- name: Install packages
  package:
    name:
      - suricata # IDS
      - jq  # Command-line JSON processor
      - ethtool # Query or control network driver and hardware settings
      - build-essential # For compiling Intel driver
      - linux-tools-generic # Installing Perf for testing
      - linux-tools-5.4.0-72-generic # Installing Perf for testing
      - sysstat # For CPU utilization output
    state: latest

- name: Install Intel i40e kernel module
  block:
    - name: Make sure directory exists
      file:
        path: /opt/i40e
        state: directory
      notify:
        - Install i40e

    - name: Unarchive driver stored locally
      unarchive:
        src: ../files/i40e-2.14.13.tar.gz
        dest: /opt/i40e/
        creates: i40e-2.14.13

- name: Stop irqbalance for high performance optimisation 
  service:
    name: irqbalance
    state: stopped

- name: Set irq affinity
  command: "/opt/i40e/i40e-2.14.13/scripts/set_irq_affinity {{irq_affinity_cpu}} {{monitor_if}}" # "local" means NUMA 0.

- name: Configure NIC
  ignore_errors: yes
  block:
    - name: Change the number of RSS queues
      command: "ethtool -L {{monitor_if}} combined {{afpacket_threads * 2}}"

    - name: Enable receive hashing offload
      command: "ethtool -K {{monitor_if}} rxhash on"

    - name: Enable Rx ntuple filters and actions
      command: "ethtool -K {{monitor_if}} ntuple on"

    - name: Allow symmetric hashing by using low entropy toeplitz key
      command: "ethtool -X {{monitor_if}} hkey 6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A:6D:5A equal {{afpacket_threads * 2}}"

    - name: Disable RX/TX pause.
      command: "ethtool -A {{monitor_if}} rx off tx off"

    - name: Adaptive control is disabled for lowest possible latency
      command: "ethtool -C {{monitor_if}} adaptive-rx off adaptive-tx off rx-usecs 125" # TODO: test e.g. 150

    - name: Changes the number of ring entries for the Rx ring. # TODO: test
      command: "ethtool -G {{monitor_if}} rx 1024" # buffer størrelse, finnes en maks størrelse men kan teste med mindre

    - name: Make sure the RSS hash function is Toeplitz.
      command: "ethtool -X {{monitor_if}} hfunc toeplitz"

    - name: Let the NIC balance as much as possible # TODO: test sdfn vs sd
      shell: |
        for proto in tcp4 udp4 tcp6 udp6; do
          ethtool -N {{monitor_if}} rx-flow-hash $proto sdfn
        done

- name: Configure suricata  
  template:  
    src: suricata.yaml.j2  
    dest: /etc/suricata/suricata.yaml 

- name: Update signatures
  command: suricata-update

- name: Restart suricata
  service:
    name: suricata
    state: restarted
    enabled: yes

# ------------------- START TESTING --------------------

- name: Testing
  tags:
    - test
  block:

    - name: Create timestamped dir for storing results
      file:
        path: "results/{{test_name}}/{{ansible_date_time.date}}"
        state: directory
        mode: "0755"
      register: newdir_res # Use this fact to store results in the right dir.
      delegate_to: localhost
      become: false

    - name: Run perf for cache miss stats
      command: "perf stat -e LLC-loads,LLC-load-misses,LLC-stores,LLC-prefetches -o /tmp/perf.txt -C 1-15,32-47 sleep {{test_seconds}}" # TODO: cpu var
      async: "{{test_seconds * 2 | int}}" # Don't wait for result. Async value longer than command runtime.
      poll: 0 # Don't wait for result

    - name: Pause for testing
      pause:
        seconds: "{{test_seconds}}"

    - name: Fetch perf stats
      fetch:
        src: /tmp/perf.txt
        dest: "{{newdir_res.path}}/perf.txt"
        flat: yes # Override file path name

    - name: Generate suri-stats plot
      command: "suri-stats -p -c {{counters}} -S -o /tmp/plot.png /var/log/suricata/stats.log"

    - name: Fetch plot
      fetch:
        src: /tmp/plot.png
        dest: "{{newdir_res.path}}/plot.png"
        flat: yes

    - name: Fetch suricata.log
      fetch:
        src: /var/log/suricata/suricata.log
        dest: "{{newdir_res.path}}/suricata.log"
        flat: yes

    - name: Fetch stats.log
      fetch:
        src: /var/log/suricata/stats.log
        dest: "{{newdir_res.path}}/stats.log"
        flat: yes