# monitor_if: "{{MONITOR_IF}}"
monitor_if: "eno1" # $ sudo lshw -class network -short

afpacket_interface: "{{monitor_if}}"
# afpacket_threads: "{{(ansible_processor_vcpus/2) | int}}" # Use half of available threads
afpacket_threads: 16 # Threads in each CPU group
afpacket_clustertype: "cluster_qm" # To bind Suricata to RSS queues
afpacket_defrag: "no"
afpacket_usemmap: "yes"
afpacket_mmaplocked: "yes"
afpacket_tpacketv3: "yes"
afpacket_ringsize: 100000
afpacket_blocksize: 1048576

threading_management_cpu: '0'
threading_receive_cpu: '"0-10"'
threading_worker_cpu: '"1-15", "32-47"'
irq_affinity_cpu: "{{threading_worker_cpu}}"
threading_worker_prio_low: ""
threading_worker_prio_medium: ""
threading_worker_prio_high: ""
threading_worker_prio_default: "high"

max_pending_packets: 65500 # Default is 1024
runmode: "workers" # default is autofp
default_packet_size: 9000 # see 'maxmtu' result when $ ip -d link list


# Testing
counters: "capture.kernel_packets,capture.kernel_drops" # Comma separated. Which counters to plot with suri-stats.
test_seconds: 5 # How long to test.
test_name: test1 # Which test is it? Remember to change this in each test. Used to make result dir.
